FROM node:18-alpine AS build

WORKDIR /frontend

COPY frontend/package.json frontend/package-lock.json ./

RUN npm ci

COPY frontend ./

WORKDIR /frontend

# You can override this when building:
#   VITE_API_BASE="http://localhost:8765" npm run build
ARG VITE_API_BASE=http://localhost:8765
ENV VITE_API_BASE=${VITE_API_BASE}

RUN npm run build

FROM nginx:alpine AS runtime

COPY --from=build /frontend/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
